#!/bin/bash

function testsFailed() {
    command -v osascript > /dev/null && osascript -e 'display notification "Precommit tests failed" with title "Tests failed"';
}

git diff --cached --name-status | grep ".js"
js_changed=$?

if [ $js_changed -eq 0 ]; then
    echo "Changes to javascript files found -- running javascript style checks and tests"
    yarn run jest
    if [ $? -ne 0 ]
    then
        echo "Javascript test failures found"
        echo "Bypass this check by running with --no-verify"
        testsFailed;
        exit 1
    fi
fi
